import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function seedAlcoholCalculation() {
    try {
        await prisma.drink_formula.deleteMany({});
        await prisma.drink_formula.createMany({
            skipDuplicates: true,
            data: [
                { drinkName: 'Lager', drinkVolume: 'Pint', drinkPriceUK: 4.68, drinkPriceLondon: 6.95, drinkCalories: 222, drinkUnits: 2, sourceLink: 'https://www.nhs.uk/live-well/alcohol-advice/calories-in-alcohol/' },
                { drinkName: 'Lager', drinkVolume: 'Half', drinkPriceUK: 2.34, drinkPriceLondon: 3.45, drinkCalories: 111, drinkUnits: 1 },
                { drinkName: 'Lager', drinkVolume: 'Bottle', drinkPriceUK: 3.80, drinkPriceLondon: 5.75, drinkCalories: 116, drinkUnits: 1 },

                { drinkName: 'Ale', drinkVolume: 'Pint', drinkPriceUK: 3.60, drinkPriceLondon: 5.75, drinkCalories: 222, drinkUnits: 2 },
                { drinkName: 'Ale', drinkVolume: 'Half', drinkPriceUK: 1.80, drinkPriceLondon: 2.85, drinkCalories: 111, drinkUnits: 1 },
                { drinkName: 'Ale', drinkVolume: 'Bottle', drinkPriceUK: 2.80, drinkPriceLondon: 3.65, drinkCalories: 167, drinkUnits: 1 },

                { drinkName: 'Stout', drinkVolume: 'Pint', drinkPriceUK: 3.60, drinkPriceLondon: 6.65, drinkCalories: 250, drinkUnits: 2 },
                { drinkName: 'Stout', drinkVolume: 'Half', drinkPriceUK: 1.80, drinkPriceLondon: 3.33, drinkCalories: 125, drinkUnits: 1 },
                { drinkName: 'Stout', drinkVolume: 'Bottle', drinkPriceUK: 2.80, drinkPriceLondon: 5, drinkCalories: 167, drinkUnits: 1 },

                { drinkName: 'Wine', drinkVolume: '175ml', drinkPriceUK: 3.59, drinkPriceLondon: 9.45, drinkCalories: 178, drinkUnits: 2.1 },
                { drinkName: 'Wine', drinkVolume: '250ml', drinkPriceUK: 5.19, drinkPriceLondon: 12.85, drinkCalories: 254, drinkUnits: 3 },
                { drinkName: 'Wine', drinkVolume: '750ml', drinkPriceUK: 12.49, drinkPriceLondon: 35.75, drinkCalories: 763, drinkUnits: 9 },

                { drinkName: 'Gin', drinkVolume: '25', drinkPriceUK: 3.60, drinkPriceLondon: 7.25, drinkCalories: 52, drinkUnits: 1 },
                { drinkName: 'Gin', drinkVolume: '50', drinkPriceUK: 7.20, drinkPriceLondon: 11.25, drinkCalories: 104, drinkUnits: 2 },

                { drinkName: 'Vodka', drinkVolume: '25', drinkPriceUK: 3.60, drinkPriceLondon: 7.25, drinkCalories: 96, drinkUnits: 1 },
                { drinkName: 'Vodka', drinkVolume: '50', drinkPriceUK: 7.20, drinkPriceLondon: 11.25, drinkCalories: 192, drinkUnits: 2 },

                { drinkName: 'Rum', drinkVolume: '25', drinkPriceUK: 3.60, drinkPriceLondon: 7.25, drinkCalories: 54, drinkUnits: 1 },
                { drinkName: 'Rum', drinkVolume: '50', drinkPriceUK: 7.20, drinkPriceLondon: 11.25, drinkCalories: 108, drinkUnits: 2 },

                { drinkName: 'Tequila', drinkVolume: '25', drinkPriceUK: 3.60, drinkPriceLondon: 7.25, drinkCalories: 48, drinkUnits: 1 },
                { drinkName: 'Tequila', drinkVolume: '50', drinkPriceUK: 7.20, drinkPriceLondon: 11.25, drinkCalories: 96, drinkUnits: 2 },

                { drinkName: 'Whiskey', drinkVolume: '25', drinkPriceUK: 3.60, drinkPriceLondon: 7.25, drinkCalories: 59, drinkUnits: 1 },
                { drinkName: 'Whiskey', drinkVolume: '50', drinkPriceUK: 7.20, drinkPriceLondon: 11.25, drinkCalories: 118, drinkUnits: 2 },

                { drinkName: 'Other', drinkVolume: '25', drinkPriceUK: 3.60, drinkPriceLondon: 7.25, drinkCalories: 54, drinkUnits: 1 },
                { drinkName: 'Other', drinkVolume: '50', drinkPriceUK: 7.20, drinkPriceLondon: 11.25, drinkCalories: 108, drinkUnits: 2 }
            ],
        });
        console.log('Alcohol calculations(cost, units, calories) data inserted successfully.');
    } catch (error) {
        console.error('Error seeding Alcohol calculations data:', error);
    } finally {
        await prisma.$disconnect();
    }
}

seedAlcoholCalculation();

async function seedDrinkingInsights() {
    try {
        await prisma.drinking_insights.deleteMany({});
        const insightsData = [
            // Insights for Male AGE_16_24
            { ageGroup: "AGE_16_24", gender: "MALE", habit: "Non-drinker", insight: "35% of men your age are also non-drinkers." },
            { ageGroup: "AGE_16_24", gender: "MALE", habit: "Up to 14 units", insight: "35% of men your age drink less than you." },
            { ageGroup: "AGE_16_24", gender: "MALE", habit: "14-21 units", insight: "81% of men your age drink less than you." },
            { ageGroup: "AGE_16_24", gender: "MALE", habit: "21-35 units", insight: "87% of men your age drink less than you." },
            { ageGroup: "AGE_16_24", gender: "MALE", habit: "35-50 units", insight: "91% of men your age drink less than you." },
            { ageGroup: "AGE_16_24", gender: "MALE", habit: "More than 50 units", insight: "93% of men your age drink less than you." },

            // Insights for Female AGE_16_24
            { ageGroup: "AGE_16_24", gender: "FEMALE", habit: "Non-drinker", insight: "58% of women your age drink less than you." },
            { ageGroup: "AGE_16_24", gender: "FEMALE", habit: "Up to 14 units", insight: "58% of women your age drink more than you." },
            { ageGroup: "AGE_16_24", gender: "FEMALE", habit: "14-21 units", insight: "89% of women your age drink more than you." },
            { ageGroup: "AGE_16_24", gender: "FEMALE", habit: "21-35 units", insight: "95% of women your age drink more than you." },
            { ageGroup: "AGE_16_24", gender: "FEMALE", habit: "More than 35 units", insight: "99% of women your age drink more than you." },

            // Insights for Other AGE_16_24
            // { ageGroup: "", gender: "", habit: "", insight: ""},
            { ageGroup: "AGE_16_24", gender: "OTHER", habit: "Non-drinker", insight: "38% of people your age are non-drinkers like you" },
            { ageGroup: "AGE_16_24", gender: "OTHER", habit: "Up to 14 units", insight: "85% of people your age drink up to 14 units a week" },
            { ageGroup: "AGE_16_24", gender: "OTHER", habit: "14-35 units", insight: "11% of people your age also drink at dangerous levels" },
            { ageGroup: "AGE_16_24", gender: "OTHER", habit: "More than 35 units", insight: "4% of people your age drink high risk amounts like you" },

            // Insights for Male AGE_25_34
            { ageGroup: "AGE_25_34", gender: "MALE", habit: "Non-drinker", insight: "17% of men your age are also non-drinkers." },
            { ageGroup: "AGE_25_34", gender: "MALE", habit: "Up to 14 units", insight: "17% of men your age drink less than you." },
            { ageGroup: "AGE_25_34", gender: "MALE", habit: "14-21 units", insight: "76% of men your age drink less than you." },
            { ageGroup: "AGE_25_34", gender: "MALE", habit: "21-35 units", insight: "87% of men your age drink less than you." },
            { ageGroup: "AGE_25_34", gender: "MALE", habit: "35-50 units", insight: "96% of men your age drink less than you." },
            { ageGroup: "AGE_25_34", gender: "MALE", habit: "More than 50 units", insight: "100% of men your age drink less than you." },

            // Insights for Female AGE_25_34
            { ageGroup: "AGE_25_34", gender: "FEMALE", habit: "Non-drinker", insight: "75% of women your age drink less than you." },
            { ageGroup: "AGE_25_34", gender: "FEMALE", habit: "Up to 14 units", insight: "25% of women your age drink more than you." },
            { ageGroup: "AGE_25_34", gender: "FEMALE", habit: "14-21 units", insight: "89% of women your age drink more than you." },
            { ageGroup: "AGE_25_34", gender: "FEMALE", habit: "21-35 units", insight: "95% of women your age drink more than you." },
            { ageGroup: "AGE_25_34", gender: "FEMALE", habit: "More than 35 units", insight: "99% of women your age drink more than you." },

            // Insights for Other AGE_25_34
            // { ageGroup: "", gender: "", habit: "", insight: ""},
            { ageGroup: "AGE_25_34", gender: "OTHER", habit: "Non-drinker", insight: "21% of people your age are non-drinkers like you" },
            { ageGroup: "AGE_25_34", gender: "OTHER", habit: "Up to 14 units", insight: "83% of people your age drink up to 14 units a week" },
            { ageGroup: "AGE_25_34", gender: "OTHER", habit: "14-35 units", insight: "14% of people your age also drink at dangerous levels" },
            { ageGroup: "AGE_25_34", gender: "OTHER", habit: "More than 35 units", insight: "3% of people your age drink high risk amounts like you" },

            // Insights for Male AGE_35_44
            { ageGroup: "AGE_35_44", gender: "MALE", habit: "Non-drinker", insight: "19% of men your age are also non-drinkers." },
            { ageGroup: "AGE_35_44", gender: "MALE", habit: "Up to 14 units", insight: "19% of men your age drink less than you." },
            { ageGroup: "AGE_35_44", gender: "MALE", habit: "14-21 units", insight: "72% of men your age drink less than you." },
            { ageGroup: "AGE_35_44", gender: "MALE", habit: "21-35 units", insight: "85% of men your age drink less than you." },
            { ageGroup: "AGE_35_44", gender: "MALE", habit: "35-50 units", insight: "94% of men your age drink less than you." },
            { ageGroup: "AGE_35_44", gender: "MALE", habit: "More than 50 units", insight: "97% of men your age drink less than you." },

            // Insights for Female AGE_35_44
            { ageGroup: "AGE_35_44", gender: "FEMALE", habit: "Non-drinker", insight: "77% of women your age drink less than you." },
            { ageGroup: "AGE_35_44", gender: "FEMALE", habit: "Up to 14 units", insight: "23% of women your age drink more than you." },
            { ageGroup: "AGE_35_44", gender: "FEMALE", habit: "14-21 units", insight: "87% of women your age drink more than you." },
            { ageGroup: "AGE_35_44", gender: "FEMALE", habit: "21-35 units", insight: "93% of women your age drink more than you." },
            { ageGroup: "AGE_35_44", gender: "FEMALE", habit: "More than 35 units", insight: "99% of women your age drink more than you." },

            // Insights for Other AGE_35_44
            // { ageGroup: "", gender: "", habit: "", insight: ""},
            { ageGroup: "AGE_35_44", gender: "OTHER", habit: "Non-drinker", insight: "21% of people your age are non-drinkers like you" },
            { ageGroup: "AGE_35_44", gender: "OTHER", habit: "Up to 14 units", insight: "80% of people your age drink up to 14 units a week" },
            { ageGroup: "AGE_35_44", gender: "OTHER", habit: "14-35 units", insight: "18% of people your age also drink at dangerous levels" },
            { ageGroup: "AGE_35_44", gender: "OTHER", habit: "More than 35 units", insight: "3% of people your age drink high risk amounts like you" },

            // Insights for Male AGE_45_54
            { ageGroup: "AGE_45_54", gender: "MALE", habit: "Non-drinker", insight: "17% of men your age are also non-drinkers." },
            { ageGroup: "AGE_45_54", gender: "MALE", habit: "Up to 14 units", insight: "17% of men your age drink less than you." },
            { ageGroup: "AGE_45_54", gender: "MALE", habit: "14-21 units", insight: "72% of men your age drink less than you." },
            { ageGroup: "AGE_45_54", gender: "MALE", habit: "21-35 units", insight: "81% of men your age drink less than you." },
            { ageGroup: "AGE_45_54", gender: "MALE", habit: "35-50 units", insight: "90% of men your age drink less than you." },
            { ageGroup: "AGE_45_54", gender: "MALE", habit: "More than 50 units", insight: "95% of men your age drink less than you." },

            // Insights for Female AGE_45_54
            { ageGroup: "AGE_45_54", gender: "FEMALE", habit: "Non-drinker", insight: "89% of women your age drink more than you." },
            { ageGroup: "AGE_45_54", gender: "FEMALE", habit: "Up to 14 units", insight: "21% of women your age drink more than you." },
            { ageGroup: "AGE_45_54", gender: "FEMALE", habit: "14-21 units", insight: "79% of women your age drink more than you." },
            { ageGroup: "AGE_45_54", gender: "FEMALE", habit: "21-35 units", insight: "88% of women your age drink more than you." },
            { ageGroup: "AGE_45_54", gender: "FEMALE", habit: "More than 35 units", insight: "98% of women your age drink more than you." },

            // Insights for Other AGE_45_54
            // { ageGroup: "", gender: "", habit: "", insight: ""},
            { ageGroup: "AGE_45_54", gender: "OTHER", habit: "Non-drinker", insight: "19% of people your age are non-drinkers like you" },
            { ageGroup: "AGE_45_54", gender: "OTHER", habit: "Up to 14 units", insight: "76% of people your age drink up to 14 units a week" },
            { ageGroup: "AGE_45_54", gender: "OTHER", habit: "14-35 units", insight: "20% of people your age also drink at dangerous levels" },
            { ageGroup: "AGE_45_54", gender: "OTHER", habit: "More than 35 units", insight: "4% of people your age drink high risk amounts like you" },

            // Insights for Male AGE_55_64
            { ageGroup: "AGE_55_64", gender: "MALE", habit: "Non-drinker", insight: "14% of men your age are also non-drinkers." },
            { ageGroup: "AGE_55_64", gender: "MALE", habit: "Up to 14 units", insight: "14% of men your age drink less than you." },
            { ageGroup: "AGE_55_64", gender: "MALE", habit: "14-21 units", insight: "64% of men your age drink less than you." },
            { ageGroup: "AGE_55_64", gender: "MALE", habit: "21-35 units", insight: "75% of men your age drink less than you." },
            { ageGroup: "AGE_55_64", gender: "MALE", habit: "35-50 units", insight: "87% of men your age drink less than you." },
            { ageGroup: "AGE_55_64", gender: "MALE", habit: "More than 50 units", insight: "93% of men your age drink less than you." },

            // Insights for Female AGE_55_64
            { ageGroup: "AGE_55_64", gender: "FEMALE", habit: "Non-drinker", insight: "17% of women your age drink less than you." },
            { ageGroup: "AGE_55_64", gender: "FEMALE", habit: "Up to 14 units", insight: "17% of women your age drink more than you." },
            { ageGroup: "AGE_55_64", gender: "FEMALE", habit: "14-21 units", insight: "79% of women your age drink more than you." },
            { ageGroup: "AGE_55_64", gender: "FEMALE", habit: "21-35 units", insight: "89% of women your age drink more than you." },
            { ageGroup: "AGE_55_64", gender: "FEMALE", habit: "More than 35 units", insight: "99% of women your age drink more than you." },

            // Insights for Other AGE_55_64
            // { ageGroup: "", gender: "", habit: "", insight: ""},
            { ageGroup: "AGE_55_64", gender: "OTHER", habit: "Non-drinker", insight: "15% of people your age are non-drinkers like you" },
            { ageGroup: "AGE_55_64", gender: "OTHER", habit: "Up to 14 units", insight: "71% of people your age drink up to 14 units a week" },
            { ageGroup: "AGE_55_64", gender: "OTHER", habit: "14-35 units", insight: "23% of people your age also drink at dangerous levels" },
            { ageGroup: "AGE_55_64", gender: "OTHER", habit: "More than 35 units", insight: "5% of people your age drink high risk amounts like you" },

            // Insights for Male AGE_65_74
            { ageGroup: "AGE_65_74", gender: "MALE", habit: "Non-drinker", insight: "12% of men your age are also non-drinkers." },
            { ageGroup: "AGE_65_74", gender: "MALE", habit: "Up to 14 units", insight: "12% of men your age drink less than you." },
            { ageGroup: "AGE_65_74", gender: "MALE", habit: "14-21 units", insight: "64% of men your age drink less than you." },
            { ageGroup: "AGE_65_74", gender: "MALE", habit: "21-35 units", insight: "77% of men your age drink less than you." },
            { ageGroup: "AGE_65_74", gender: "MALE", habit: "35-50 units", insight: "91% of men your age drink less than you." },
            { ageGroup: "AGE_65_74", gender: "MALE", habit: "More than 50 units", insight: "95% of men your age drink less than you." },

            // Insights for Female AGE_65_74
            { ageGroup: "AGE_65_74", gender: "FEMALE", habit: "Non-drinker", insight: "19% of women your age drink less than you." },
            { ageGroup: "AGE_65_74", gender: "FEMALE", habit: "Up to 14 units", insight: "19% of women your age drink more than you." },
            { ageGroup: "AGE_65_74", gender: "FEMALE", habit: "14-21 units", insight: "83% of women your age drink more than you." },
            { ageGroup: "AGE_65_74", gender: "FEMALE", habit: "21-35 units", insight: "90% of women your age drink more than you." },
            { ageGroup: "AGE_65_74", gender: "FEMALE", habit: "More than 35 units", insight: "99% of women your age drink more than you." },

            // Insights for Other AGE_65_74
            // { ageGroup: "", gender: "", habit: "", insight: ""},
            { ageGroup: "AGE_65_74", gender: "OTHER", habit: "Non-drinker", insight: "15% of people your age are non-drinkers like you" },
            { ageGroup: "AGE_65_74", gender: "OTHER", habit: "Up to 14 units", insight: "73% of people your age drink up to 14 units a week" },
            { ageGroup: "AGE_65_74", gender: "OTHER", habit: "14-35 units", insight: "23% of people your age also drink at dangerous levels" },
            { ageGroup: "AGE_65_74", gender: "OTHER", habit: "More than 35 units", insight: "4% of people your age drink high risk amounts like you" },

            // Insights for Male AGE_OVER_75
            { ageGroup: "AGE_OVER_75", gender: "MALE", habit: "Non-drinker", insight: "20% of men your age are also non-drinkers." },
            { ageGroup: "AGE_OVER_75", gender: "MALE", habit: "Up to 14 units", insight: "20% of men your age drink less than you." },
            { ageGroup: "AGE_OVER_75", gender: "MALE", habit: "14-21 units", insight: "77% of men your age drink less than you." },
            { ageGroup: "AGE_OVER_75", gender: "MALE", habit: "21-35 units", insight: "86% of men your age drink less than you." },
            { ageGroup: "AGE_OVER_75", gender: "MALE", habit: "35-50 units", insight: "93% of men your age drink less than you." },
            { ageGroup: "AGE_OVER_75", gender: "MALE", habit: "More than 50 units", insight: "95% of men your age drink less than you." },

            // Insights for Female AGE_OVER_75
            { ageGroup: "AGE_OVER_75", gender: "FEMALE", habit: "Non-drinker", insight: "26% of women your age drink less than you." },
            { ageGroup: "AGE_OVER_75", gender: "FEMALE", habit: "Up to 14 units", insight: "26% of women your age drink more than you." },
            { ageGroup: "AGE_OVER_75", gender: "FEMALE", habit: "14-21 units", insight: "89% of women your age drink more than you." },
            { ageGroup: "AGE_OVER_75", gender: "FEMALE", habit: "21-35 units", insight: "95% of women your age drink more than you." },
            { ageGroup: "AGE_OVER_75", gender: "FEMALE", habit: "More than 35 units", insight: "99% of women your age drink more than you." },

            // Insights for Other AGE_OVER_75
            // { ageGroup: "", gender: "", habit: "", insight: ""},
            { ageGroup: "AGE_OVER_75", gender: "OTHER", habit: "Non-drinker", insight: "23% of people your age are non-drinkers like you" },
            { ageGroup: "AGE_OVER_75", gender: "OTHER", habit: "Up to 14 units", insight: "84% of people your age drink up to 14 units a week" },
            { ageGroup: "AGE_OVER_75", gender: "OTHER", habit: "14-35 units", insight: "13% of people your age also drink at dangerous levels" },
            { ageGroup: "AGE_OVER_75", gender: "OTHER", habit: "More than 35 units", insight: "2% of people your age drink high risk amounts like you" },
        ]

        await prisma.drinking_insights.createMany({
            skipDuplicates: true,
            data: insightsData,
        });

        console.log('Drinking insights data inserted successfully.');
    } catch (error) {
        console.error('Error seeding Drinking insights data:', error);
    } finally {
        await prisma.$disconnect();
    }
}

seedDrinkingInsights();


async function seedDrinkingInsightsBasedOnPlace() {
    try {
        await prisma.drinking_insights_based_on_place.deleteMany({});
        const insightsData = [
            { place: "LONDON", habit: "Non-drinker", insight: "In London 17% of people are non-drinkers like you" },
            { place: "LONDON", habit: "Up to 14 units", insight: "In London 50% of drinkers drink within the recommended levels like you" },
            { place: "LONDON", habit: "14-50 units", insight: "In London 19% of people drink harmful levels of alcohol like you" },
            { place: "LONDON", habit: "More than 50 units", insight: "In London 3% of people drink harmful levels of alcohol like you" },


            { place: "NORTH_EAST", habit: "Non-drinker", insight: "In North East 17% of people are non-drinkers like you" },
            { place: "NORTH_EAST", habit: "Up to 14 units", insight: "In North East 59% of drinkers drink within the recommended levels like you" },
            { place: "NORTH_EAST", habit: "14-50 units", insight: "In North East 24% of people drink harmful levels of alcohol like you" },
            { place: "NORTH_EAST", habit: "More than 50 units", insight: "In North East 5% of people drink harmful levels of alcohol like you" },


            { place: "NORTH_WEST", habit: "Non-drinker", insight: "In North West 17% of people are non-drinkers like you" },
            { place: "NORTH_WEST", habit: "Up to 14 units", insight: "In North West 54% of drinkers drink within the recommended levels like you" },
            { place: "NORTH_WEST", habit: "14-50 units", insight: "In North West 21% of people drink harmful levels of alcohol like you" },
            { place: "NORTH_WEST", habit: "More than 50 units", insight: "In North West 3% of people drink harmful levels of alcohol like you" },


            { place: "YORKSHIRE_AND_HUMBER", habit: "Non-drinker", insight: "In Yorkshire and Humber 17% of people are non-drinkers like you" },
            { place: "YORKSHIRE_AND_HUMBER", habit: "Up to 14 units", insight: "In Yorkshire and Humber 61% of drinkers drink within the recommended levels like you" },
            { place: "YORKSHIRE_AND_HUMBER", habit: "14-50 units", insight: "In Yorkshire and Humber 22% of people drink harmful levels of alcohol like you" },
            { place: "YORKSHIRE_AND_HUMBER", habit: "More than 50 units", insight: "In Yorkshire and Humber 3% of people drink harmful levels of alcohol like you" },


            { place: "EAST_MIDLANDS", habit: "Non-drinker", insight: "In East Midlands 17% of people are non-drinkers like you" },
            { place: "EAST_MIDLANDS", habit: "Up to 14 units", insight: "In East Midlands 54% of drinkers drink within the recommended levels like you" },
            { place: "EAST_MIDLANDS", habit: "14-50 units", insight: "In East Midlands 29% of people drink harmful levels of alcohol like you" },
            { place: "EAST_MIDLANDS", habit: "More than 50 units", insight: "In East Midlands 6% of people drink harmful levels of alcohol like you" },


            { place: "WEST_MIDLANDS", habit: "Non-drinker", insight: "In West Midlands 17% of people are non-drinkers like you" },
            { place: "WEST_MIDLANDS", habit: "Up to 14 units", insight: "In West Midlands 54% of drinkers drink within the recommended levels like you" },
            { place: "WEST_MIDLANDS", habit: "14-50 units", insight: "In West Midlands 15% of people drink harmful levels of alcohol like you" },
            { place: "WEST_MIDLANDS", habit: "More than 50 units", insight: "In West Midlands 2% of people drink harmful levels of alcohol like you" },


            { place: "EAST_OF_ENGLAND", habit: "Non-drinker", insight: "In East of England 17% of people are non-drinkers like you" },
            { place: "EAST_OF_ENGLAND", habit: "Up to 14 units", insight: "In East of England 65% of drinkers drink within the recommended levels like you" },
            { place: "EAST_OF_ENGLAND", habit: "14-50 units", insight: "In East of England 18% of people drink harmful levels of alcohol like you" },
            { place: "EAST_OF_ENGLAND", habit: "More than 50 units", insight: "In East of England 4% of people drink harmful levels of alcohol like you" },


            { place: "SOUTH_EAST", habit: "Non-drinker", insight: "In South East 17% of people are non-drinkers like you" },
            { place: "SOUTH_EAST", habit: "Up to 14 units", insight: "In South East 59% of drinkers drink within the recommended levels like you" },
            { place: "SOUTH_EAST", habit: "14-50 units", insight: "In South East 21% of people drink harmful levels of alcohol like you" },
            { place: "SOUTH_EAST", habit: "More than 50 units", insight: "In South East 3% of people drink harmful levels of alcohol like you" },


            { place: "SOUTH_WEST", habit: "Non-drinker", insight: "In South West 17% of people are non-drinkers like you" },
            { place: "SOUTH_WEST", habit: "Up to 14 units", insight: "In South West 61% of drinkers drink within the recommended levels like you" },
            { place: "SOUTH_WEST", habit: "14-50 units", insight: "In South West 25% of people drink harmful levels of alcohol like you" },
            { place: "SOUTH_WEST", habit: "More than 50 units", insight: "In South West 5% of people drink harmful levels of alcohol like you" },


            { place: "SCOTLAND", habit: "Non-drinker", insight: "In Scotland 19% of people are non-drinkers like you" },
            { place: "SCOTLAND", habit: "Up to 14 units", insight: "In Scotland 58% of drinkers drink within the recommended levels like you" },
            { place: "SCOTLAND", habit: "14-50 units", insight: "In Scotland 22% of people drink harmful levels of alcohol like you" },


            { place: "WALES", habit: "Non-drinker", insight: "In Wales 17% of people are non-drinkers like you" },
            { place: "WALES", habit: "Up to 14 units", insight: "In Wales 66% of drinkers drink within the recommended levels like you" },
            { place: "WALES", habit: "14-50 units", insight: "In Wales 14% of people drink harmful levels of alcohol like you" },


            { place: "NORTHERN_IRELAND", habit: "Non-drinker", insight: "In Northern Ireland 23% of people are non-drinkers like you" },
            { place: "NORTHERN_IRELAND", habit: "Up to 14 units", insight: "In Northern Ireland 57% of drinkers drink within the recommended levels like you" },
            { place: "NORTHERN_IRELAND", habit: "14-50 units", insight: "In Northern Ireland 14% of people drink harmful levels of alcohol like you" },


            { place: "OTHER", habit: "Non-drinker", insight: "In England 21% of people are non-drinkers like you" },
            { place: "OTHER", habit: "Up to 14 units", insight: "In England 57% of drinkers drink within the recommended levels like you" },
            { place: "OTHER", habit: "14-50 units", insight: "In England 21% of people drink harmful levels of alcohol like you" },
        ]

        await prisma.drinking_insights_based_on_place.createMany({
            skipDuplicates: true,
            data: insightsData,
        });

        console.log('Drinking insights based on place data inserted successfully.');
    } catch (error) {
        console.error('Error seeding Drinking insights based on place data:', error);
    } finally {
        await prisma.$disconnect();
    }
}

seedDrinkingInsightsBasedOnPlace();

const yorkshire = ["BB18",
    "BB8",
    "BD1",
    "BD10",
    "BD11",
    "BD12",
    "BD13",
    "BD14",
    "BD15",
    "BD16",
    "BD17",
    "BD18",
    "BD19",
    "BD2",
    "BD20",
    "BD21",
    "BD22",
    "BD23",
    "BD24",
    "BD3",
    "BD4",
    "BD5",
    "BD6",
    "BD7",
    "BD8",
    "BD9",
    "BD97",
    "BD98",
    "BD99",
    "DN1",
    "DN10",
    "DN11",
    "DN12",
    "DN14",
    "DN15",
    "DN16",
    "DN17",
    "DN18",
    "DN19",
    "DN2",
    "DN20",
    "DN21",
    "DN3",
    "DN31",
    "DN32",
    "DN33",
    "DN34",
    "DN35",
    "DN36",
    "DN37",
    "DN38",
    "DN39",
    "DN4",
    "DN40",
    "DN41",
    "DN5",
    "DN55",
    "DN6",
    "DN7",
    "DN8",
    "DN9",
    "HD1",
    "HD2",
    "HD3",
    "HD4",
    "HD5",
    "HD6",
    "HD7",
    "HD8",
    "HD9",
    "HG1",
    "HG2",
    "HG3",
    "HG4",
    "HG5",
    "HU1",
    "HU10",
    "HU11",
    "HU12",
    "HU13",
    "HU14",
    "HU15",
    "HU16",
    "HU17",
    "HU18",
    "HU19",
    "HU2",
    "HU20",
    "HU3",
    "HU4",
    "HU5",
    "HU6",
    "HU7",
    "HU8",
    "HU9",
    "HX1",
    "HX2",
    "HX3",
    "HX4",
    "HX5",
    "HX6",
    "HX7",
    "LA10",
    "LA19",
    "LA2",
    "LN3",
    "LN7",
    "LN8",
    "LS1",
    "LS10",
    "LS11",
    "LS12",
    "LS13",
    "LS14",
    "LS15",
    "LS16",
    "LS17",
    "LS18",
    "LS19",
    "LS2",
    "LS20",
    "LS21",
    "LS22",
    "LS23",
    "LS24",
    "LS25",
    "LS26",
    "LS27",
    "LS28",
    "LS29",
    "LS3",
    "LS4",
    "LS5",
    "LS6",
    "LS7",
    "LS8",
    "LS88",
    "LS9",
    "LS98",
    "LS99",
    "OL14",
    "OL15",
    "PR2",
    "S1",
    "S10",
    "S11",
    "S12",
    "S13",
    "S14",
    "S17",
    "S19",
    "S2",
    "S20",
    "S21",
    "S25",
    "S26",
    "S3",
    "S30",
    "S31",
    "S32",
    "S35",
    "S36",
    "S4",
    "S5",
    "S6",
    "S60",
    "S61",
    "S62",
    "S63",
    "S64",
    "S65",
    "S66",
    "S7",
    "S70",
    "S71",
    "S72",
    "S73",
    "S74",
    "S75",
    "S8",
    "S80",
    "S81",
    "S9",
    "S95",
    "S96",
    "S97",
    "S98",
    "S99",
    "WF1",
    "WF10",
    "WF11",
    "WF12",
    "WF13",
    "WF14",
    "WF15",
    "WF16",
    "WF17",
    "WF2",
    "WF3",
    "WF4",
    "WF5",
    "WF6",
    "WF7",
    "WF8",
    "WF9",
    "WF90",
    "YO1",
    "YO10",
    "YO11",
    "YO12",
    "YO13",
    "YO14",
    "YO15",
    "YO16",
    "YO17",
    "YO18",
    "YO19",
    "YO2",
    "YO21",
    "YO22",
    "YO23",
    "YO24",
    "YO25",
    "YO26",
    "YO3",
    "YO30",
    "YO31",
    "YO32",
    "YO4",
    "YO41",
    "YO42",
    "YO43",
    "YO5",
    "YO51",
    "YO6",
    "YO60",
    "YO61",
    "YO62",
    "YO7",
    "YO8",
    "YO90",
    "YO91",
    "YO95"]

const northEast = ["CA1",
    "CA10",
    "CA11",
    "CA12",
    "CA13",
    "CA14",
    "CA15",
    "CA16",
    "CA17",
    "CA18",
    "CA19",
    "CA2",
    "CA20",
    "CA21",
    "CA22",
    "CA23",
    "CA24",
    "CA25",
    "CA26",
    "CA27",
    "CA28",
    "CA3",
    "CA4",
    "CA5",
    "CA6",
    "CA7",
    "CA8",
    "CA9",
    "CA95",
    "CA99",
    "DG16",
    "DH1",
    "DH2",
    "DH3",
    "DH4",
    "DH5",
    "DH6",
    "DH7",
    "DH8",
    "DH9",
    "DH97",
    "DH98",
    "DH99",
    "DL1",
    "DL10",
    "DL11",
    "DL12",
    "DL13",
    "DL14",
    "DL15",
    "DL16",
    "DL17",
    "DL2",
    "DL3",
    "DL4",
    "DL5",
    "DL6",
    "DL7",
    "DL8",
    "DL9",
    "DL98",
    "NE1",
    "NE10",
    "NE11",
    "NE12",
    "NE13",
    "NE15",
    "NE16",
    "NE17",
    "NE18",
    "NE19",
    "NE2",
    "NE20",
    "NE21",
    "NE22",
    "NE23",
    "NE24",
    "NE25",
    "NE26",
    "NE27",
    "NE28",
    "NE29",
    "NE3",
    "NE30",
    "NE31",
    "NE32"]

const eastMidlands = ["LU1",
    "LU2",
    "LU3",
    "LU4",
    "LU5",
    "LU6",
    "LU7",
    "MK1",
    "MK10",
    "MK11",
    "MK12",
    "MK13",
    "MK14",
    "MK15",
    "MK16",
    "MK17",
    "MK19",
    "MK2",
    "MK3",
    "MK4",
    "MK40",
    "MK41",
    "MK42",
    "MK43",
    "MK44",
    "MK45",
    "MK46",
    "MK5",
    "MK6",
    "MK7",
    "MK8",
    "MK9",
    "NN10",
    "NN29",
    "NN7",
    "NN8",
    "NN9",
    "PE1",
    "PE12",
    "PE13",
    "PE14",
    "PE15",
    "PE16",
    "PE17",
    "PE18",
    "PE19",
    "PE2",
    "PE26",
    "PE27",
    "PE28",
    "PE29",
    "PE3",
    "PE30",
    "PE31",
    "PE32",
    "PE33",
    "PE34",
    "PE35",
    "PE36",
    "PE37",
    "PE38",
    "PE4",
    "PE5",
    "PE6",
    "PE7",
    "PE8",
    "PE9",
    "SG1",
    "SG10",
    "SG11",
    "SG12",
    "SG13",
    "SG14",
    "SG15",
    "SG16",
    "SG17",
    "SG18",
    "SG19",
    "SG2",
    "SG3",
    "SG4",
    "SG5",
    "SG6",
    "SG7",
    "SG8",
    "SG9"]


const westMidlands = ["B1",
    "B2",
    "B3",
    "B4",
    "B5",
    "B6",
    "B7",
    "B8",
    "B9",
    "B10",
    "B11",
    "B12",
    "B13",
    "B14",
    "B15",
    "B16",
    "B17",
    "B18",
    "B19",
    "B20",
    "B21",
    "B23",
    "B24",
    "B25",
    "B26",
    "B27",
    "B28",
    "B29",
    "B30",
    "B31",
    "B32",
    "B33",
    "B34",
    "B35",
    "B36",
    "B37",
    "B38",
    "B40",
    "B42",
    "B43",
    "B44",
    "B45",
    "B46",
    "B47",
    "B48",
    "B49",
    "B50",
    "B60",
    "B61",
    "B62",
    "B63",
    "B64",
    "B65",
    "B66",
    "B67",
    "B68",
    "B69",
    "B70",
    "B71",
    "B72",
    "B73",
    "B74",
    "B75",
    "B76",
    "B77",
    "B78",
    "B79",
    "B80",
    "B90",
    "B91",
    "B92",
    "B93",
    "B94",
    "B95",
    "B96",
    "B97",
    "B98",
    "B99",
    "CV1",
    "CV2",
    "CV3",
    "CV4",
    "CV5",
    "CV6",
    "CV7",
    "CV8",
    "CV9",
    "CV10",
    "CV11",
    "CV12",
    "CV13",
    "CV21",
    "CV22",
    "CV23",
    "CV31",
    "CV32",
    "CV33",
    "CV34",
    "CV35",
    "CV36",
    "CV37",
    "CV47",
    "DY1",
    "DY2",
    "DY3",
    "DY4",
    "DY5",
    "DY6",
    "DY7",
    "DY8",
    "DY9",
    "DY10",
    "DY11",
    "DY12",
    "DY13",
    "DY14",
    "HR1",
    "HR2",
    "HR3",
    "HR4",
    "HR5",
    "HR6",
    "HR7",
    "HR8",
    "HR9",
    "ST1",
    "ST2",
    "ST3",
    "ST4",
    "ST5",
    "ST6",
    "ST7",
    "ST8",
    "ST9",
    "ST10",
    "ST11",
    "ST12",
    "ST13",
    "ST14",
    "ST15",
    "ST16",
    "ST17",
    "ST18",
    "ST19",
    "ST20",
    "ST21",
    "TF1",
    "TF2",
    "TF3",
    "TF4",
    "TF5",
    "TF6",
    "TF7",
    "TF8",
    "TF9",
    "TF10",
    "TF11",
    "TF12",
    "TF13",
    "WR1",
    "WR2",
    "WR3",
    "WR4",
    "WR5",
    "WR6",
    "WR7",
    "WR8",
    "WR9",
    "WR10",
    "WR11",
    "WR12",
    "WR13",
    "WR14",
    "WR15",
    "WS1",
    "WS2",
    "WS3",
    "WS4",
    "WS5",
    "WS6",
    "WS7",
    "WS8",
    "WS9",
    "WS10",
    "WS11",
    "WS",
    "WV1",
    "WV2",
    "WV3",
    "WV4",
    "WV5",
    "WV6",
    "WV7",
    "WV8",
    "WV9",
    "WV10",
    "WV11",
    "W"]

const southWest = ["BA1",
    "BA10",
    "BA11",
    "BA12",
    "BA13",
    "BA14",
    "BA15",
    "BA16",
    "BA2",
    "BA20",
    "BA21",
    "BA22",
    "BA3",
    "BA4",
    "BA5",
    "BA6",
    "BA7",
    "BA8",
    "BA9",
    "BH1",
    "BH10",
    "BH11",
    "BH12",
    "BH13",
    "BH14",
    "BH15",
    "BH16",
    "BH17",
    "BH18",
    "BH19",
    "BH2",
    "BH20",
    "BH21",
    "BH22",
    "BH23",
    "BH24",
    "BH3",
    "BH31",
    "BH4",
    "BH5",
    "BH6",
    "BH7",
    "BH8",
    "BH9",
    "BS0",
    "BS1",
    "BS10",
    "BS11",
    "BS12",
    "BS13",
    "BS14",
    "BS15",
    "BS16",
    "BS17",
    "BS18",
    "BS19",
    "BS2",
    "BS20",
    "BS21",
    "BS22",
    "BS23",
    "BS24",
    "BS25",
    "BS26",
    "BS27",
    "BS28",
    "BS29",
    "BS3",
    "BS30",
    "BS31",
    "BS32",
    "BS34",
    "BS35",
    "BS36",
    "BS37",
    "BS39",
    "BS4",
    "BS40",
    "BS41",
    "BS48",
    "BS49",
    "BS5",
    "BS6",
    "BS7",
    "BS77",
    "BS8",
    "BS80",
    "BS9",
    "BS98",
    "BS99",
    "DT1",
    "DT10",
    "DT11",
    "DT2",
    "DT3",
    "DT4",
    "DT5",
    "DT6",
    "DT7",
    "DT8",
    "DT9",
    "EX1",
    "EX10",
    "EX11",
    "EX12",
    "EX13",
    "EX14",
    "EX15",
    "EX16",
    "EX17",
    "EX18",
    "EX19",
    "EX2",
    "EX20",
    "EX21",
    "EX22",
    "EX23",
    "EX24",
    "EX3",
    "EX31",
    "EX32",
    "EX33",
    "EX34",
    "EX35",
    "EX36",
    "EX37",
    "EX38",
    "EX39",
    "EX4",
    "EX5",
    "EX6",
    "EX7",
    "EX8",
    "EX9",
    "GL1",
    "GL10",
    "GL11",
    "GL12",
    "GL13",
    "GL14",
    "GL15",
    "GL16",
    "GL17",
    "GL18",
    "GL19",
    "GL2",
    "GL20",
    "GL3",
    "GL4",
    "GL5",
    "GL50",
    "GL51",
    "GL52",
    "GL53",
    "GL54",
    "GL55",
    "GL56",
    "GL6",
    "GL7",
    "GL8",
    "GL9",
    "HR8",
    "HR9",
    "NP16",
    "NP25",
    "NP5",
    "NP6",
    "OX18",
    "OX7",
    "OX8",
    "PL1",
    "PL10",
    "PL11",
    "PL12",
    "PL13",
    "PL14",
    "PL15",
    "PL16",
    "PL17",
    "PL18",
    "PL19",
    "PL2",
    "PL20",
    "PL21",
    "PL22",
    "PL23",
    "PL24",
    "PL25",
    "PL26",
    "PL27",
    "PL28",
    "PL29",
    "PL3",
    "PL30",
    "PL31",
    "PL32",
    "PL33",
    "PL34",
    "PL35",
    "PL4",
    "PL5",
    "PL6",
    "PL7",
    "PL8",
    "PL9",
    "PL95",
    "RG17",
    "SN1",
    "SN10",
    "SN11",
    "SN12",
    "SN13",
    "SN14",
    "SN15",
    "SN16",
    "SN17",
    "SN2",
    "SN25",
    "SN26",
    "SN3",
    "SN38",
    "SN4",
    "SN5",
    "SN6",
    "SN7",
    "SN8",
    "SN9",
    "SN99",
    "SO5",
    "SO51",
    "SP1",
    "SP11",
    "SP2",
    "SP3",
    "SP4",
    "SP5",
    "SP6",
    "SP7",
    "SP8",
    "SP9",
    "TA1",
    "TA10",
    "TA11",
    "TA12",
    "TA13",
    "TA14",
    "TA15",
    "TA16",
    "TA17",
    "TA18",
    "TA19",
    "TA2",
    "TA20",
    "TA21",
    "TA22",
    "TA23",
    "TA24",
    "TA3",
    "TA4",
    "TA5",
    "TA6",
    "TA7",
    "TA8",
    "TA9",
    "TQ1",
    "TQ10",
    "TQ11",
    "TQ12",
    "TQ13",
    "TQ14",
    "TQ2",
    "TQ3",
    "TQ4",
    "TQ5",
    "TQ6",
    "TQ7",
    "TQ8",
    "TQ9",
    "TR1",
    "TR10",
    "TR11",
    "TR12",
    "TR13",
    "TR14",
    "TR15",
    "TR16",
    "TR17",
    "TR18",
    "TR19",
    "TR2",
    "TR20",
    "TR21",
    "TR22",
    "TR23",
    "TR24",
    "TR25",
    "TR26",
    "TR27",
    "TR3",
    "TR4",
    "TR5",
    "TR6",
    "TR7",
    "TR8",
    "TR9",
    "TR93",
    "WR11",
    "WR12",
    "WR13",
    "WR8",
]

const southEast = ["BH21",
    "BH23",
    "BH24",
    "BH25",
    "BH31",
    "BN1",
    "BN10",
    "BN11",
    "BN12",
    "BN13",
    "BN14",
    "BN15",
    "BN16",
    "BN17",
    "BN18",
    "BN2",
    "BN20",
    "BN21",
    "BN22",
    "BN23",
    "BN24",
    "BN25",
    "BN26",
    "BN27",
    "BN3",
    "BN4",
    "BN41",
    "BN42",
    "BN43",
    "BN44",
    "BN45",
    "BN5",
    "BN50",
    "BN51",
    "BN52",
    "BN6",
    "BN7",
    "BN8",
    "BN88",
    "BN9",
    "BN95",
    "BN99",
    "BR6",
    "BR8",
    "CR2",
    "CR3",
    "CR5",
    "CR6",
    "CR8",
    "CT1",
    "CT10",
    "CT11",
    "CT12",
    "CT13",
    "CT14",
    "CT15",
    "CT16",
    "CT17",
    "CT18",
    "CT19",
    "CT2",
    "CT20",
    "CT21",
    "CT3",
    "CT4",
    "CT5",
    "CT50",
    "CT6",
    "CT7",
    "CT8",
    "CT9",
    "DA1",
    "DA10",
    "DA11",
    "DA12",
    "DA13",
    "DA14",
    "DA17",
    "DA2",
    "DA3",
    "DA4",
    "DA5",
    "DA9",
    "GL56",
    "GL7",
    "GU1",
    "GU10",
    "GU11",
    "GU12",
    "GU13",
    "GU14",
    "GU15",
    "GU16",
    "GU17",
    "GU18",
    "GU19",
    "GU2",
    "GU20",
    "GU21",
    "GU22",
    "GU23",
    "GU24",
    "GU25",
    "GU26",
    "GU27",
    "GU28",
    "GU29",
    "GU3",
    "GU30",
    "GU31",
    "GU32",
    "GU33",
    "GU34",
    "GU35",
    "GU4",
    "GU46",
    "GU47",
    "GU5",
    "GU51",
    "GU52",
    "GU6",
    "GU7",
    "GU8",
    "GU9",
    "GU95",
    "HP10",
    "HP11",
    "HP12",
    "HP13",
    "HP14",
    "HP15",
    "HP16",
    "HP17",
    "HP18",
    "HP19",
    "HP20",
    "HP21",
    "HP22",
    "HP23",
    "HP27",
    "HP4",
    "HP5",
    "HP6",
    "HP7",
    "HP8",
    "HP9",
    "KT10",
    "KT11",
    "KT12",
    "KT13",
    "KT14",
    "KT15",
    "KT16",
    "KT17",
    "KT18",
    "KT19",
    "KT2",
    "KT20",
    "KT21",
    "KT22",
    "KT23",
    "KT24",
    "KT4",
    "KT6",
    "KT7",
    "KT8",
    "KT9",
    "LU6",
    "LU7",
    "ME1",
    "ME10",
    "ME11",
    "ME12",
    "ME13",
    "ME14",
    "ME15",
    "ME16",
    "ME17",
    "ME18",
    "ME19",
    "ME2",
    "ME20",
    "ME3",
    "ME4",
    "ME5",
    "ME6",
    "ME7",
    "ME8",
    "ME9",
    "ME99",
    "MK1",
    "MK17",
    "MK18",
    "MK19",
    "NN12",
    "NN13",
    "OX1",
    "OX10",
    "OX11",
    "OX12",
    "OX13",
    "OX14",
    "OX15",
    "OX16",
    "OX17",
    "OX18",
    "OX2",
    "OX20",
    "OX25",
    "OX26",
    "OX27",
    "OX28",
    "OX29",
    "OX3",
    "OX33",
    "OX39",
    "OX4",
    "OX44",
    "OX49",
    "OX5",
    "OX6",
    "OX7",
    "OX8",
    "OX9",
    "PO1",
    "PO10",
    "PO11",
    "PO12",
    "PO13",
    "PO14",
    "PO15",
    "PO16",
    "PO17",
    "PO18",
    "PO19",
    "PO2",
    "PO20",
    "PO21",
    "PO22",
    "PO3",
    "PO30",
    "PO31",
    "PO32",
    "PO33",
    "PO34",
    "PO35",
    "PO36",
    "PO37",
    "PO38",
    "PO39",
    "PO4",
    "PO40",
    "PO41",
    "PO5",
    "PO6",
    "PO7",
    "PO8",
    "PO9",
    "RG1",
    "RG10",
    "RG11",
    "RG12",
    "RG13",
    "RG14",
    "RG15",
    "RG16",
    "RG17",
    "RG18",
    "RG19",
    "RG2",
    "RG20",
    "RG21",
    "RG22",
    "RG23",
    "RG24",
    "RG25",
    "RG26",
    "RG27",
    "RG28",
    "RG29",
    "RG3",
    "RG30",
    "RG31",
    "RG4",
    "RG40",
    "RG41",
    "RG42",
    "RG45",
    "RG5",
    "RG6",
    "RG7",
    "RG8",
    "RG9",
    "RH1",
    "RH10",
    "RH11",
    "RH12",
    "RH13",
    "RH14",
    "RH15",
    "RH16",
    "RH17",
    "RH18",
    "RH19",
    "RH2",
    "RH20",
    "RH3",
    "RH4",
    "RH5",
    "RH6",
    "RH7",
    "RH77",
    "RH8",
    "RH9",
    "SL0",
    "SL1",
    "SL2",
    "SL3",
    "SL4",
    "SL5",
    "SL6",
    "SL60",
    "SL7",
    "SL8",
    "SL9",
    "SL95",
    "SM2",
    "SM3",
    "SM5",
    "SM7",
    "SN6",
    "SN7",
    "SN8",
    "SO1",
    "SO14",
    "SO15",
    "SO16",
    "SO17",
    "SO18",
    "SO19",
    "SO2",
    "SO20",
    "SO21",
    "SO22",
    "SO23",
    "SO24",
    "SO25",
    "SO3",
    "SO30",
    "SO31",
    "SO32",
    "SO4",
    "SO40",
    "SO41",
    "SO42",
    "SO43",
    "SO45",
    "SO5",
    "SO50",
    "SO51",
    "SO52",
    "SO53",
    "SO9",
    "SO97",
    "SP10",
    "SP11",
    "SP4",
    "SP5",
    "SP6",
    "SP9",
    "TN1",
    "TN10",
    "TN11",
    "TN12",
    "TN13",
    "TN14",
    "TN15",
    "TN16",
    "TN17",
    "TN18",
    "TN19",
    "TN2",
    "TN20",
    "TN21",
    "TN22",
    "TN23",
    "TN24",
    "TN25",
    "TN26",
    "TN27",
    "TN28",
    "TN29",
    "TN3",
    "TN30",
    "TN31",
    "TN32",
    "TN33",
    "TN34",
    "TN35",
    "TN36",
    "TN37",
    "TN38",
    "TN39",
    "TN4",
    "TN40",
    "TN5",
    "TN6",
    "TN7",
    "TN8",
    "TN9",
    "TW12",
    "TW14",
    "TW15",
    "TW16",
    "TW17",
    "TW18",
    "TW19",
    "TW20",
    "TW6",
    "UB8",
    "UB9",
    "WD3"]

const eastOfEngland = ["AL1",
    "AL10",
    "AL2",
    "AL3",
    "AL4",
    "AL5",
    "AL6",
    "AL7",
    "AL8",
    "AL9",
    "CB1",
    "CB10",
    "CB11",
    "CB2",
    "CB21",
    "CB22",
    "CB23",
    "CB24",
    "CB25",
    "CB3",
    "CB4",
    "CB5",
    "CB6",
    "CB7",
    "CB8",
    "CB9",
    "CM0",
    "CM1",
    "CM11",
    "CM12",
    "CM13",
    "CM14",
    "CM15",
    "CM16",
    "CM17",
    "CM18",
    "CM19",
    "CM2",
    "CM20",
    "CM21",
    "CM22",
    "CM23",
    "CM24",
    "CM3",
    "CM4",
    "CM5",
    "CM6",
    "CM7",
    "CM77",
    "CM8",
    "CM9",
    "CM92",
    "CM98",
    "CM99",
    "CO1",
    "CO10",
    "CO11",
    "CO12",
    "CO13",
    "CO14",
    "CO15",
    "CO16",
    "CO2",
    "CO3",
    "CO4",
    "CO5",
    "CO6",
    "CO7",
    "CO8",
    "CO9",
    "E4",
    "EN10",
    "EN11",
    "EN2",
    "EN4",
    "EN5",
    "EN6",
    "EN7",
    "EN8",
    "EN9",
    "HA5",
    "HA6",
    "HA7",
    "HP1",
    "HP2",
    "HP23",
    "HP3",
    "HP4",
    "HP5",
    "HP8",
    "IG10",
    "IG4",
    "IG7",
    "IG8",
    "IG9",
    "IP1",
    "IP10",
    "IP11",
    "IP12",
    "IP13",
    "IP14",
    "IP15",
    "IP16",
    "IP17",
    "IP18",
    "IP19",
    "IP2",
    "IP20",
    "IP21",
    "IP22",
    "IP23",
    "IP24",
    "IP25",
    "IP26",
    "IP27",
    "IP28",
    "IP29",
    "IP3",
    "IP30",
    "IP31",
    "IP32",
    "IP33",
    "IP4",
    "IP5",
    "IP6",
    "IP7",
    "IP8",
    "IP9",
    "IP98",
    "LU1",
    "LU2",
    "LU3",
    "LU4",
    "LU5",
    "LU6",
    "LU7",
    "LU95",
    "MK1",
    "MK10",
    "MK11",
    "MK12",
    "MK13",
    "MK14",
    "MK15",
    "MK16",
    "MK17",
    "MK19",
    "MK2",
    "MK3",
    "MK4",
    "MK40",
    "MK41",
    "MK42",
    "MK43",
    "MK44",
    "MK45",
    "MK46",
    "MK5",
    "MK6",
    "MK7",
    "MK77",
    "MK8",
    "MK9",
    "MK98",
    "NN10",
    "NN29",
    "NN7",
    "NN8",
    "NN9",
    "NR1",
    "NR10",
    "NR11",
    "NR12",
    "NR13",
    "NR14",
    "NR15",
    "NR16",
    "NR17",
    "NR18",
    "NR19",
    "NR2",
    "NR20",
    "NR21",
    "NR22",
    "NR23",
    "NR24",
    "NR25",
    "NR26",
    "NR27",
    "NR28",
    "NR29",
    "NR3",
    "NR30",
    "NR31",
    "NR32",
    "NR33",
    "NR34",
    "NR35",
    "NR4",
    "NR5",
    "NR6",
    "NR7",
    "NR8",
    "NR9",
    "NR99",
    "PE1",
    "PE12",
    "PE13",
    "PE14",
    "PE15",
    "PE16",
    "PE17",
    "PE18",
    "PE19",
    "PE2",
    "PE26",
    "PE27",
    "PE28",
    "PE29",
    "PE3",
    "PE30",
    "PE31",
    "PE32",
    "PE33",
    "PE34",
    "PE35",
    "PE36",
    "PE37",
    "PE38",
    "PE4",
    "PE5",
    "PE6",
    "PE7",
    "PE8",
    "PE9",
    "PE99",
    "RM14",
    "RM15",
    "RM16",
    "RM17",
    "RM18",
    "RM19",
    "RM20",
    "RM4",
    "SG1",
    "SG10",
    "SG11",
    "SG12",
    "SG13",
    "SG14",
    "SG15",
    "SG16",
    "SG17",
    "SG18",
    "SG19",
    "SG2",
    "SG3",
    "SG4",
    "SG5",
    "SG6",
    "SG7",
    "SG8",
    "SG9",
    "SL9",
    "SS0",
    "SS1",
    "SS11",
    "SS12",
    "SS13",
    "SS14",
    "SS15",
    "SS16",
    "SS17",
    "SS2",
    "SS22",
    "SS3",
    "SS4",
    "SS5",
    "SS6",
    "SS7",
    "SS8",
    "SS9",
    "SS99",
    "UB9",
    "WD1",
    "WD17",
    "WD18",
    "WD19",
    "WD2",
    "WD23",
    "WD24",
    "WD25",
    "WD3",
    "WD4",
    "WD5",
    "WD6",
    "WD7",
    "WD99"]

const northWest = ["BB0",
    "BB1",
    "BB10",
    "BB11",
    "BB12",
    "BB18",
    "BB2",
    "BB3",
    "BB4",
    "BB5",
    "BB6",
    "BB7",
    "BB8",
    "BB9",
    "BB94",
    "BD23",
    "BL0",
    "BL1",
    "BL11",
    "BL2",
    "BL3",
    "BL4",
    "BL5",
    "BL6",
    "BL7",
    "BL78",
    "BL8",
    "BL9",
    "CH1",
    "CH2",
    "CH25",
    "CH26",
    "CH27",
    "CH28",
    "CH29",
    "CH3",
    "CH30",
    "CH31",
    "CH32",
    "CH33",
    "CH34",
    "CH4",
    "CH41",
    "CH42",
    "CH43",
    "CH44",
    "CH45",
    "CH46",
    "CH47",
    "CH48",
    "CH49",
    "CH60",
    "CH61",
    "CH62",
    "CH63",
    "CH64",
    "CH65",
    "CH66",
    "CH70",
    "CH88",
    "CH99",
    "CW1",
    "CW10",
    "CW11",
    "CW12",
    "CW2",
    "CW3",
    "CW4",
    "CW5",
    "CW6",
    "CW7",
    "CW8",
    "CW9",
    "CW98",
    "FY0",
    "FY1",
    "FY2",
    "FY3",
    "FY4",
    "FY5",
    "FY6",
    "FY7",
    "FY8",
    "L1",
    "L10",
    "L11",
    "L12",
    "L13",
    "L14",
    "L15",
    "L16",
    "L17",
    "L18",
    "L19",
    "L2",
    "L20",
    "L21",
    "L22",
    "L23",
    "L24",
    "L25",
    "L26",
    "L27",
    "L28",
    "L29",
    "L3",
    "L30",
    "L31",
    "L32",
    "L33",
    "L34",
    "L35",
    "L36",
    "L37",
    "L38",
    "L39",
    "L4",
    "L40",
    "L41",
    "L42",
    "L43",
    "L44",
    "L45",
    "L46",
    "L47",
    "L48",
    "L49",
    "L5",
    "L6",
    "L60",
    "L61",
    "L62",
    "L63",
    "L64",
    "L65",
    "L66",
    "L67",
    "L68",
    "L69",
    "L7",
    "L70",
    "L71",
    "L72",
    "L73",
    "L74",
    "L75",
    "L8",
    "L80",
    "L9",
    "LA1",
    "LA10",
    "LA11",
    "LA12",
    "LA13",
    "LA14",
    "LA15",
    "LA16",
    "LA17",
    "LA18",
    "LA19",
    "LA2",
    "LA20",
    "LA21",
    "LA22",
    "LA23",
    "LA3",
    "LA4",
    "LA5",
    "LA6",
    "LA7",
    "LA8",
    "LA9",
    "M1",
    "M10",
    "M11",
    "M12",
    "M13",
    "M14",
    "M15",
    "M16",
    "M17",
    "M18",
    "M19",
    "M2",
    "M20",
    "M21",
    "M22",
    "M23",
    "M24",
    "M25",
    "M26",
    "M27",
    "M28",
    "M29",
    "M3",
    "M30",
    "M31",
    "M32",
    "M33",
    "M34",
    "M35",
    "M38",
    "M4",
    "M40",
    "M41",
    "M43",
    "M44",
    "M45",
    "M46",
    "M5",
    "M50",
    "M52",
    "M6",
    "M60",
    "M61",
    "M7",
    "M8",
    "M9",
    "M90",
    "M99",
    "OL1",
    "OL10",
    "OL11",
    "OL12",
    "OL13",
    "OL14",
    "OL15",
    "OL16",
    "OL2",
    "OL3",
    "OL4",
    "OL5",
    "OL6",
    "OL7",
    "OL8",
    "OL9",
    "OL95",
    "PR0",
    "PR1",
    "PR11",
    "PR2",
    "PR25",
    "PR26",
    "PR3",
    "PR4",
    "PR5",
    "PR6",
    "PR7",
    "PR8",
    "PR9",
    "SK1",
    "SK10",
    "SK11",
    "SK12",
    "SK13",
    "SK14",
    "SK15",
    "SK16",
    "SK2",
    "SK22",
    "SK23",
    "SK3",
    "SK4",
    "SK5",
    "SK6",
    "SK7",
    "SK8",
    "SK9",
    "ST7",
    "SY13",
    "SY14",
    "TF9",
    "WA1",
    "WA10",
    "WA11",
    "WA12",
    "WA13",
    "WA14",
    "WA15",
    "WA16",
    "WA2",
    "WA3",
    "WA4",
    "WA5",
    "WA55",
    "WA6",
    "WA7",
    "WA8",
    "WA88",
    "WA9",
    "WN1",
    "WN2",
    "WN3",
    "WN4",
    "WN5",
    "WN6",
    "WN7",
    "WN8"]

const scotland = ["AB1",
    "AB10",
    "AB11",
    "AB12",
    "AB13",
    "AB14",
    "AB15",
    "AB16",
    "AB2",
    "AB21",
    "AB22",
    "AB23",
    "AB24",
    "AB25",
    "AB3",
    "AB30",
    "AB31",
    "AB32",
    "AB33",
    "AB34",
    "AB35",
    "AB36",
    "AB37",
    "AB38",
    "AB39",
    "AB4",
    "AB41",
    "AB42",
    "AB43",
    "AB44",
    "AB45",
    "AB5",
    "AB51",
    "AB52",
    "AB53",
    "AB54",
    "AB55",
    "AB56",
    "AB9",
    "AB99",
    "DD1",
    "DD10",
    "DD11",
    "DD2",
    "DD3",
    "DD4",
    "DD5",
    "DD6",
    "DD7",
    "DD8",
    "DD9",
    "DG1",
    "DG10",
    "DG11",
    "DG12",
    "DG13",
    "DG14",
    "DG16",
    "DG2",
    "DG3",
    "DG4",
    "DG5",
    "DG6",
    "DG7",
    "DG8",
    "DG9",
    "EH1",
    "EH10",
    "EH11",
    "EH12",
    "EH13",
    "EH14",
    "EH15",
    "EH16",
    "EH17",
    "EH18",
    "EH19",
    "EH2",
    "EH20",
    "EH21",
    "EH22",
    "EH23",
    "EH25",
    "EH24",
    "EH26",
    "EH27",
    "EH28",
    "EH29",
    "EH3",
    "EH30",
    "EH31",
    "EH32",
    "EH33",
    "EH34",
    "EH35",
    "EH37",
    "EH39",
    "EH38",
    "EH4",
    "EH40",
    "EH41",
    "EH42",
    "EH43",
    "EH44",
    "EH45",
    "EH46",
    "EH47",
    "EH48",
    "EH49",
    "EH5",
    "EH51",
    "EH52",
    "EH53",
    "EH54",
    "EH55",
    "EH6",
    "EH7",
    "EH77",
    "EH8",
    "EH9",
    "EH91",
    "EH95",
    "EH99",
    "FK1",
    "FK10",
    "FK11",
    "FK12",
    "FK13",
    "FK14",
    "FK15",
    "FK16",
    "FK17",
    "FK19",
    "FK2",
    "FK18",
    "FK21",
    "FK3",
    "FK20",
    "FK4",
    "FK5",
    "FK6",
    "FK7",
    "FK8",
    "FK9",
    "G1",
    "G11",
    "G12",
    "G13",
    "G14",
    "G15",
    "G2",
    "G20",
    "G21",
    "G22",
    "G23",
    "G3",
    "G31",
    "G32",
    "G33",
    "G34",
    "G4",
    "G40",
    "G41",
    "G42",
    "G43",
    "G44",
    "G45",
    "G46",
    "G5",
    "G51",
    "G52",
    "G53",
    "G58",
    "G59",
    "G60",
    "G61",
    "G62",
    "G63",
    "G64",
    "G65",
    "G66",
    "G67",
    "G68",
    "G69",
    "G70",
    "G71",
    "G72",
    "G73",
    "G74",
    "G75",
    "G76",
    "G77",
    "G78",
    "G79",
    "G80",
    "G81",
    "G82",
    "G83",
    "G84",
    "G9",
    "G90",
    "HS1",
    "HS2",
    "HS3",
    "HS4",
    "HS5",
    "HS6",
    "HS7",
    "HS9",
    "IV1",
    "HS8",
    "IV10",
    "IV11",
    "IV12",
    "IV13",
    "IV14",
    "IV15",
    "IV16",
    "IV17",
    "IV18",
    "IV19",
    "IV2",
    "IV20",
    "IV21",
    "IV22",
    "IV23",
    "IV25",
    "IV26",
    "IV27",
    "IV24",
    "IV28",
    "IV3",
    "IV30",
    "IV31",
    "IV32",
    "IV33",
    "IV34",
    "IV35",
    "IV36",
    "IV4",
    "IV40",
    "IV42",
    "IV43",
    "IV44",
    "IV47",
    "IV49",
    "IV5",
    "IV41",
    "IV45",
    "IV51",
    "IV52",
    "IV54",
    "IV55",
    "IV56",
    "IV6",
    "IV63",
    "IV7",
    "IV8",
    "IV9",
    "IV99",
    "KA1",
    "KA10",
    "KA11",
    "KA12",
    "KA13",
    "KA14",
    "KA15",
    "KA16",
    "KA17",
    "KA18",
    "KA19",
    "KA2",
    "KA20",
    "KA21",
    "KA22",
    "KA23",
    "KA24",
    "KA25",
    "KA26",
    "KA27",
    "KA28",
    "KA29",
    "KA3",
    "KA30",
    "KA4",
    "KA5",
    "KA6",
    "KA7",
    "KA8",
    "KA9",
    "KW1",
    "KW10",
    "KW12",
    "KW14",
    "KW11",
    "KW15",
    "KW16",
    "KW17",
    "KW3",
    "KW8",
    "KW9",
    "KY1",
    "KW5",
    "KW7",
    "KY10",
    "KY11",
    "KY12",
    "KY13",
    "KY14",
    "KY15",
    "KY16",
    "KY2",
    "KY3",
    "KY4",
    "KY5",
    "KY6",
    "KY7",
    "KY8",
    "KY9",
    "KY99",
    "ML1",
    "ML10",
    "ML11",
    "ML12",
    "ML2",
    "ML3",
    "ML4",
    "ML5",
    "ML6",
    "ML7",
    "ML8",
    "ML9",
    "PA1",
    "PA10",
    "PA11",
    "PA12",
    "PA13",
    "PA14",
    "PA15",
    "PA16",
    "PA17",
    "PA18",
    "PA19",
    "PA2",
    "PA20",
    "PA21",
    "PA23",
    "PA22",
    "PA28",
    "PA24",
    "PA27",
    "PA29",
    "PA3",
    "PA30",
    "PA31",
    "PA32",
    "PA33",
    "PA34",
    "PA35",
    "PA36",
    "PA37",
    "PA38",
    "PA39",
    "PA4",
    "PA40",
    "PA42",
    "PA43",
    "PA44",
    "PA45",
    "PA46",
    "PA48",
    "PA5",
    "PA49",
    "PA6",
    "PA60",
    "PA61",
    "PA64",
    "PA65",
    "PA66",
    "PA7",
    "PA72",
    "PA75",
    "PA76",
    "PA77",
    "PA8",
    "PA78",
    "PA82",
    "PA86",
    "PA80",
    "PA87",
    "PA88",
    "PA9",
    "PH1",
    "PH10",
    "PH11",
    "PH12",
    "PH13",
    "PH14",
    "PH15",
    "PH16",
    "PH17",
    "PH18",
    "PH19",
    "PH2",
    "PH20",
    "PH21",
    "PH22",
    "PH23",
    "PH24",
    "PH25",
    "PH26",
    "PH3",
    "PH31",
    "PH32",
    "PH33",
    "PH34",
    "PH35",
    "PH36",
    "PH4",
    "PH49",
    "PH5",
    "PH37",
    "PH38",
    "PH39",
    "PH41",
    "PH50",
    "PH6",
    "PH7",
    "PH8",
    "PH9",
    "TD1",
    "TD10",
    "TD11",
    "TD12",
    "TD14",
    "TD13",
    "TD2",
    "TD4",
    "TD15",
    "TD3",
    "TD5",
    "TD6",
    "TD7",
    "TD8",
    "TD9",
    "ZE1",
    "ZE2",
    "ZE3"]

const walesPostCodes = ["LL58",
    "LL59",
    "LL60",
    "LL61",
    "LL62",
    "LL64",
    "LL65",
    "LL66",
    "LL67",
    "LL68",
    "LL69",
    "LL70",
    "LL71",
    "LL72",
    "LL73",
    "LL74",
    "LL75",
    "LL76",
    "LL77",
    "LL78",
    "NP2",
    "NP3",
    "NP23",
    "CF31",
    "CF32",
    "CF33",
    "CF34",
    "CF35",
    "CF36",
    "CF46",
    "CF81",
    "CF82",
    "CF83",
    "NP11",
    "CF3",
    "CF5",
    "CF83",
    "SA4",
    "SA14",
    "SA15",
    "SA16",
    "SA17",
    "SA18",
    "SA19",
    "SA20",
    "SA31",
    "SA32",
    "SA33",
    "SA34",
    "SA38",
    "SA39",
    "SA40",
    "SA44",
    "SA48",
    "SA66",
    "SA38",
    "SA40",
    "SA43",
    "SA44",
    "SA45",
    "SA46",
    "SA47",
    "SA48",
    "SY20",
    "SY23",
    "SY24",
    "SY25",
    "LL16",
    "LL21",
    "LL22",
    "LL24",
    "LL25",
    "LL26",
    "LL27",
    "LL28",
    "LL29",
    "LL30",
    "LL31",
    "LL32",
    "LL33",
    "LL34",
    "LL57",
    "CH7",
    "LL11",
    "LL15",
    "LL16",
    "LL17",
    "LL18",
    "LL19",
    "LL20",
    "LL21",
    "LL22",
    "CH1",
    "CH4",
    "CH5",
    "CH6",
    "CH7",
    "CH8",
    "LL11",
    "LL12",
    "LL18",
    "LL19",
    "CF1",
    "CF5",
    "CF32",
    "CF35",
    "CF61",
    "CF62",
    "CF63",
    "CF64",
    "CF71",
    "LL21",
    "LL23",
    "LL33",
    "LL35",
    "LL36",
    "LL37",
    "LL38",
    "LL39",
    "LL40",
    "LL41",
    "LL42",
    "LL43",
    "LL44",
    "LL45",
    "LL46",
    "LL47",
    "LL48",
    "LL49",
    "LL51",
    "LL52",
    "LL53",
    "LL54",
    "LL55",
    "LL57",
    "SY20",
    "CF46",
    "CF47",
    "CF48",
    "NP4",
    "NP6",
    "NP7",
    "SA8",
    "SA9",
    "SA10",
    "SA11",
    "SA12",
    "SA13",
    "SA18",
    "CF3",
    "NP1",
    "NP10",
    "NP19",
    "NP20",
    "NP1",
    "NP2",
    "NP3",
    "SA34",
    "SA35",
    "SA36",
    "SA37",
    "SA41",
    "SA42",
    "SA43",
    "SA61",
    "SA62",
    "SA63",
    "SA64",
    "SA65",
    "SA66",
    "SA67",
    "SA68",
    "SA69",
    "SA70",
    "SA71",
    "SA72",
    "SA73",
    "CF44",
    "CF48",
    "HR3",
    "HR5",
    "LD1",
    "LD2",
    "LD3",
    "LD4",
    "LD5",
    "LD6",
    "LD7",
    "LD8",
    "NP7",
    "NP8",
    "SA9",
    "SA10",
    "SY5",
    "SY10",
    "SY15",
    "SY16",
    "SY17",
    "SY18",
    "SY19",
    "SY20",
    "SY21",
    "SY22",
    "CF37",
    "CF38",
    "CF39",
    "CF40",
    "CF41",
    "CF42",
    "CF43",
    "CF44",
    "CF45",
    "CF72",
    "SA1",
    "SA2",
    "SA3",
    "SA4",
    "SA5",
    "SA6",
    "SA7",
    "SA18",
    "NP4",
    "NP44",
    "LL11",
    "LL12",
    "LL13",
    "LL14",
    "LL20",
    "SY13",
    "SY14"]

const northernIreland = ["BT41",
    "BT61",
    "BT54",
    "BT39",
    "BT44",
    "BT43",
    "BT42",
    "BT53",
    "BT24",
    "BT32",
    "BT19",
    "BT20",
    "BT5",
    "BT4",
    "BT11",
    "BT6",
    "BT7",
    "BT8",
    "BT9",
    "BT3",
    "BT17",
    "BT2",
    "BT16",
    "BT15",
    "BT14",
    "BT13",
    "BT10",
    "BT12",
    "BT57",
    "BT38",
    "BT81",
    "BT31",
    "BT52",
    "BT51",
    "BT80",
    "BT62",
    "BT63",
    "BT64",
    "BT65",
    "BT66",
    "BT67",
    "BT29",
    "BT21",
    "BT30",
    "BT71",
    "BT70",
    "BT94",
    "BT93",
    "BT92",
    "BT75",
    "BT26",
    "BT40",
    "BT49",
    "BT27",
    "BT28",
    "BT48",
    "BT46",
    "BT45",
    "BT33",
    "BT35",
    "BT34",
    "BT37",
    "BT36",
    "BT22",
    "BT23",
    "BT78",
    "BT79",
    "BT56",
    "BT55",
    "BT82"]
async function seedPostCodes() {
    try {
        await prisma.london_post_codes.deleteMany({});
        await prisma.london_post_codes.createMany({
            skipDuplicates: true,
            data: [
                { postCode: 'E1' },
                { postCode: 'E2' },
                { postCode: 'E3' },
                { postCode: 'E4' },
                { postCode: 'E5' },
                { postCode: 'E6' },
                { postCode: 'E7' },
                { postCode: 'E8' },
                { postCode: 'E9' },
                { postCode: 'E10' },
                { postCode: 'E11' },
                { postCode: 'E12' },
                { postCode: 'E13' },
                { postCode: 'E14' },
                { postCode: 'E15' },
                { postCode: 'E16' },
                { postCode: 'E17' },
                { postCode: 'E18' },
                { postCode: 'E1W' },
                { postCode: 'E20' },
                { postCode: 'E98' },

                // City of London
                { postCode: 'EC1A' },
                { postCode: 'EC1M' },
                { postCode: 'EC1N' },
                { postCode: 'EC1P' },
                { postCode: 'EC1R' },
                { postCode: 'EC1V' },
                { postCode: 'EC1Y' },
                { postCode: 'EC2A' },
                { postCode: 'EC2M' },
                { postCode: 'EC2N' },
                { postCode: 'EC2P' },
                { postCode: 'EC2R' },
                { postCode: 'EC2V' },
                { postCode: 'EC2Y' },
                { postCode: 'EC3A' },
                { postCode: 'EC3M' },
                { postCode: 'EC3N' },
                { postCode: 'EC3P' },
                { postCode: 'EC3R' },
                { postCode: 'EC3V' },
                { postCode: 'EC4A' },
                { postCode: 'EC4M' },
                { postCode: 'EC4N' },
                { postCode: 'EC4P' },
                { postCode: 'EC4R' },
                { postCode: 'EC4V' },
                { postCode: 'EC4Y' },

                // North London
                { postCode: 'N1' },
                { postCode: 'N2' },
                { postCode: 'N3' },
                { postCode: 'N4' },
                { postCode: 'N5' },
                { postCode: 'N6' },
                { postCode: 'N7' },
                { postCode: 'N8' },
                { postCode: 'N9' },
                { postCode: 'N10' },
                { postCode: 'N11' },
                { postCode: 'N12' },
                { postCode: 'N13' },
                { postCode: 'N14' },
                { postCode: 'N15' },
                { postCode: 'N16' },
                { postCode: 'N17' },
                { postCode: 'N18' },
                { postCode: 'N19' },
                { postCode: 'N1C' },
                { postCode: 'N1P' },
                { postCode: 'N20' },
                { postCode: 'N21' },
                { postCode: 'N22' },
                { postCode: 'N81' },

                // Northwest London
                { postCode: 'NW1' },
                { postCode: 'NW2' },
                { postCode: 'NW3' },
                { postCode: 'NW4' },
                { postCode: 'NW5' },
                { postCode: 'NW6' },
                { postCode: 'NW7' },
                { postCode: 'NW8' },
                { postCode: 'NW9' },
                { postCode: 'NW10' },
                { postCode: 'NW11' },
                { postCode: 'NW1W' },
                { postCode: 'NW26' },

                // Southeast London
                { postCode: 'SE1' },
                { postCode: 'SE2' },
                { postCode: 'SE3' },
                { postCode: 'SE4' },
                { postCode: 'SE5' },
                { postCode: 'SE6' },
                { postCode: 'SE7' },
                { postCode: 'SE8' },
                { postCode: 'SE9' },
                { postCode: 'SE10' },
                { postCode: 'SE11' },
                { postCode: 'SE12' },
                { postCode: 'SE13' },
                { postCode: 'SE14' },
                { postCode: 'SE15' },
                { postCode: 'SE16' },
                { postCode: 'SE17' },
                { postCode: 'SE18' },
                { postCode: 'SE19' },
                { postCode: 'SE1P' },
                { postCode: 'SE20' },
                { postCode: 'SE21' },
                { postCode: 'SE22' },
                { postCode: 'SE23' },
                { postCode: 'SE24' },
                { postCode: 'SE25' },
                { postCode: 'SE26' },
                { postCode: 'SE27' },
                { postCode: 'SE28' },

                // Southwest London
                { postCode: 'SW2' },
                { postCode: 'SW3' },
                { postCode: 'SW4' },
                { postCode: 'SW5' },
                { postCode: 'SW6' },
                { postCode: 'SW7' },
                { postCode: 'SW8' },
                { postCode: 'SW9' },
                { postCode: 'SW10' },
                { postCode: 'SW11' },
                { postCode: 'SW12' },
                { postCode: 'SW13' },
                { postCode: 'SW14' },
                { postCode: 'SW15' },
                { postCode: 'SW16' },
                { postCode: 'SW17' },
                { postCode: 'SW18' },
                { postCode: 'SW19' },
                { postCode: 'SW1A' },
                { postCode: 'SW1E' },
                { postCode: 'SW1H' },
                { postCode: 'SW1P' },
                { postCode: 'SW1V' },
                { postCode: 'SW1W' },
                { postCode: 'SW1X' },
                { postCode: 'SW1Y' },
                { postCode: 'SW20' },
                { postCode: 'SW95' },

                // West London
                { postCode: 'W2' },
                { postCode: 'W3' },
                { postCode: 'W4' },
                { postCode: 'W5' },
                { postCode: 'W6' },
                { postCode: 'W7' },
                { postCode: 'W8' },
                { postCode: 'W9' },
                { postCode: 'W10' },
                { postCode: 'W11' },
                { postCode: 'W12' },
                { postCode: 'W13' },
                { postCode: 'W14' },
                { postCode: 'W1A' },
                { postCode: 'W1B' },
                { postCode: 'W1C' },
                { postCode: 'W1D' },
                { postCode: 'W1F' },
                { postCode: 'W1G' },
                { postCode: 'W1H' },
                { postCode: 'W1J' },
                { postCode: 'W1K' },
                { postCode: 'W1S' },
                { postCode: 'W1T' },
                { postCode: 'W1U' },
                { postCode: 'W1W' },

                // West Central London
                { postCode: 'WC1A' },
                { postCode: 'WC1B' },
                { postCode: 'WC1E' },
                { postCode: 'WC1H' },
                { postCode: 'WC1N' },
                { postCode: 'WC1R' },
                { postCode: 'WC1V' },
                { postCode: 'WC1X' },
                { postCode: 'WC2A' },
                { postCode: 'WC2B' },
                { postCode: 'WC2E' },
                { postCode: 'WC2H' },
                { postCode: 'WC2N' },
                { postCode: 'WC2R' },

                // Additional Areas
                // Bromley
                { postCode: 'BR1' },
                { postCode: 'BR2' },
                { postCode: 'BR3' },
                { postCode: 'BR4' },
                { postCode: 'BR5' },
                { postCode: 'BR6' },
                { postCode: 'BR7' },
                { postCode: 'BR8' },

                // Croydon
                { postCode: 'CR0' },
                { postCode: 'CR2' },
                { postCode: 'CR3' },
                { postCode: 'CR4' },
                { postCode: 'CR5' },
                { postCode: 'CR6' },
                { postCode: 'CR7' },
                { postCode: 'CR8' },
                { postCode: 'CR9' },
                { postCode: 'CR44' },
                { postCode: 'CR90' },

                // Dartford
                { postCode: 'DA1' },
                { postCode: 'DA5' },
                { postCode: 'DA6' },
                { postCode: 'DA7' },
                { postCode: 'DA8' },
                { postCode: 'DA14' },
                { postCode: 'DA15' },
                { postCode: 'DA16' },
                { postCode: 'DA17' },
                { postCode: 'DA18' },

                // Enfield
                { postCode: 'EN1' },
                { postCode: 'EN2' },
                { postCode: 'EN3' },
                { postCode: 'EN4' },
                { postCode: 'EN5' },
                { postCode: 'EN6' },
                { postCode: 'EN7' },
                { postCode: 'EN8' },
                { postCode: 'EN9' },

                // Harrow
                { postCode: 'HA0' },
                { postCode: 'HA1' },
                { postCode: 'HA2' },
                { postCode: 'HA3' },
                { postCode: 'HA4' },
                { postCode: 'HA5' },
                { postCode: 'HA6' },
                { postCode: 'HA7' },
                { postCode: 'HA8' },
                { postCode: 'HA9' },

                // Ilford
                { postCode: 'IG1' },
                { postCode: 'IG2' },
                { postCode: 'IG3' },
                { postCode: 'IG4' },
                { postCode: 'IG5' },
                { postCode: 'IG6' },
                { postCode: 'IG7' },
                { postCode: 'IG8' },
                { postCode: 'IG9' },
                { postCode: 'IG11' },

                // Kingston upon Thames
                { postCode: 'KT1' },
                { postCode: 'KT2' },
                { postCode: 'KT3' },
                { postCode: 'KT4' },
                { postCode: 'KT5' },
                { postCode: 'KT6' },
                { postCode: 'KT7' },
                { postCode: 'KT8' },
                { postCode: 'KT9' },
                { postCode: 'KT17' },
                { postCode: 'KT18' },
                { postCode: 'KT19' },
                { postCode: 'KT22' },

                // Romford
                { postCode: 'RM1' },
                { postCode: 'RM2' },
                { postCode: 'RM3' },
                { postCode: 'RM4' },
                { postCode: 'RM5' },
                { postCode: 'RM6' },
                { postCode: 'RM7' },
                { postCode: 'RM8' },
                { postCode: 'RM9' },
                { postCode: 'RM10' },
                { postCode: 'RM11' },
                { postCode: 'RM12' },
                { postCode: 'RM13' },
                { postCode: 'RM14' },
                { postCode: 'RM15' },

                // Sutton
                { postCode: 'SM1' },
                { postCode: 'SM2' },
                { postCode: 'SM3' },
                { postCode: 'SM4' },
                { postCode: 'SM5' },
                { postCode: 'SM6' },
                { postCode: 'SM7' },

                // Sevenoaks and Westerham
                { postCode: 'TN14' },
                { postCode: 'TN16' },

                // Twickenham
                { postCode: 'TW1' },
                { postCode: 'TW2' },
                { postCode: 'TW3' },
                { postCode: 'TW4' },
                { postCode: 'TW5' },
                { postCode: 'TW6' },
                { postCode: 'TW7' },
                { postCode: 'TW8' },
                { postCode: 'TW9' },
                { postCode: 'TW10' },
                { postCode: 'TW11' },
                { postCode: 'TW12' },
                { postCode: 'TW13' },
                { postCode: 'TW14' },
                { postCode: 'TW15' },
                { postCode: 'TW19' },


                { postCode: 'UB' },
                { postCode: 'UB1' },
                { postCode: 'UB2' },
                { postCode: 'UB3' },
                { postCode: 'UB4' },
                { postCode: 'UB5' },
                { postCode: 'UB6' },
                { postCode: 'UB7' },
                { postCode: 'UB8' },
                { postCode: 'UB9' },
                { postCode: 'UB10' },
                { postCode: 'UB11' },
                { postCode: 'UB18' },
                { postCode: 'WD' },
                { postCode: 'WD3' },
                { postCode: 'WD6' },
                { postCode: 'WD23' }
            ]
        });

        await prisma.yorkshire_post_codes.deleteMany({});
        await prisma.yorkshire_post_codes.createMany({
            skipDuplicates: true,
            data: yorkshire.map(postCode => ({ postCode: postCode }))
        });

        await prisma.north_east_post_codes.deleteMany({});
        await prisma.north_east_post_codes.createMany({
            skipDuplicates: true,
            data: northEast.map(postCode => ({ postCode: postCode }))
        })

        // await prisma.midlands_post_codes.deleteMany({});
        // await prisma.midlands_post_codes.createMany({
        //     skipDuplicates: true,
        //     data: midlands.map(postCode => ({ postCode: postCode }))
        // })

        await prisma.east_midlands_post_codes.deleteMany({});
        await prisma.east_midlands_post_codes.createMany({
            skipDuplicates: true,
            data: eastMidlands.map(postCode => ({ postCode: postCode }))
        })

        await prisma.west_midlands_post_codes.deleteMany({});
        await prisma.west_midlands_post_codes.createMany({
            skipDuplicates: true,
            data: westMidlands.map(postCode => ({ postCode: postCode }))
        })


        await prisma.south_west_post_codes.deleteMany({});
        await prisma.south_west_post_codes.createMany({
            skipDuplicates: true,
            data: southWest.map(postCode => ({ postCode: postCode }))
        })

        await prisma.south_east_post_codes.deleteMany({});
        await prisma.south_east_post_codes.createMany({
            skipDuplicates: true,
            data: southEast.map(postCode => ({ postCode: postCode }))
        })

        await prisma.east_of_england_post_codes.deleteMany({});
        await prisma.east_of_england_post_codes.createMany({
            skipDuplicates: true,
            data: eastOfEngland.map(postCode => ({ postCode: postCode }))
        })

        await prisma.north_west_post_codes.deleteMany({});
        await prisma.north_west_post_codes.createMany({
            skipDuplicates: true,
            data: northWest.map(postCode => ({ postCode: postCode }))
        })

        await prisma.scotland_post_codes.deleteMany({});
        await prisma.scotland_post_codes.createMany({
            skipDuplicates: true,
            data: scotland.map(postCode => ({ postCode: postCode }))
        })

        await prisma.wales_post_codes.deleteMany({});
        await prisma.wales_post_codes.createMany({
            skipDuplicates: true,
            data: walesPostCodes.map(postCode => ({ postCode: postCode }))
        })

        await prisma.northern_ireland_post_codes.deleteMany({});
        await prisma.northern_ireland_post_codes.createMany({
            skipDuplicates: true,
            data: northernIreland.map(postCode => ({ postCode: postCode }))
        })

        console.log('Post codes seeded successfully')
    } catch (error) {
        console.log(error)
    } finally {
        await prisma.$disconnect()
    }

}

seedPostCodes();
